### ISSUE TITLE
 AndroidRuntime: java.lang.VerifyError: Verifier rejected class ru.mobilap.tapdaq.Tapdaq due to bad method void ru.mobilap.tapdaq.Tapdaq.<init>(org.godotengine.godot.Godot)

### ISSUE THREAD

**Issue by slabgames** [DrMoriarty/godot-tapdaq#2]
Tried this plugin on 3.2.4.rc

```
03-12 18:55:01.110  8157  8157 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class ru.mobilap.tapdaq.Tapdaq due to bad method void ru.mobilap.tapdaq.Tapdaq.<init>(org.godotengine.godot.Godot) (declaration of 'ru.mobilap.tapdaq.Tapdaq' appears in /data/app/com.slabgames.game-1/base.apk:classes3.dex)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at java.lang.Class.forName(Class.java:324)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at java.lang.Class.forName(Class.java:285)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:141)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:63)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:95)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at org.godotengine.godot.Godot.onCreate(Godot.java:585)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:61)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at com.godot.game.GodotApp.onCreate(GodotApp.java:46)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6323)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.ActivityThread.access$900(ActivityThread.java:153)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5451)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-12 18:55:01.110  8157  8157 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by DrMoriarty** [comment]
updated plugin for newest godot and sdk 7.8.2
try it
